# FROM alpine as rdkit-build
# RUN apk add --no-cache sudo cmake gcc g++ make git \
#     boost-dev freetype-dev postgresql-common postgresql postgresql-dev
ARG PG_VERSION=17
ARG PG_VERSION_MINOR=9
ARG RDKIT="2024_09_6"

# https://github.com/sameersbn/docker-postgresql/blob/f5b7752b9336b89a651541cf9872e6fe5cff4e4e/Dockerfile#L1
FROM ubuntu:jammy-20250126 AS add-apt-repositories

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y wget gnupg \
 && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
 && echo 'deb http://apt.postgresql.org/pub/repos/apt/ jammy-pgdg main' >> /etc/apt/sources.list

FROM ubuntu:jammy-20250126 AS rdkit-build
USER root

ARG PG_VERSION
ARG PG_VERSION_MINOR
ARG RDKIT

ENV PG_APP_HOME="/etc/docker-postgresql" \
    PG_VERSION=${PG_VERSION} \
    PG_VERSION_MINOR=${PG_VERSION_MINOR} \
    PG_USER=postgres \
    PG_HOME=/var/lib/postgresql \
    PG_RUNDIR=/run/postgresql \
    PG_LOGDIR=/var/log/postgresql \
    PG_CERTDIR=/etc/postgresql/certs

ENV PG_BINDIR=/usr/lib/postgresql/${PG_VERSION}/bin \
    PG_DATADIR=${PG_HOME}/${PG_VERSION}/main

COPY --from=add-apt-repositories /etc/apt/trusted.gpg /etc/apt/trusted.gpg
COPY --from=add-apt-repositories /etc/apt/sources.list /etc/apt/sources.list

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y acl sudo locales \
      "postgresql-${PG_VERSION}=${PG_VERSION}.${PG_VERSION_MINOR}*" postgresql-client-${PG_VERSION} postgresql-contrib-${PG_VERSION} postgresql-server-dev-${PG_VERSION} libpq-dev \
 && update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX \
 && locale-gen en_US.UTF-8 \
 && DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales \
 && ln -sf ${PG_DATADIR}/postgresql.conf /etc/postgresql/${PG_VERSION}/main/postgresql.conf \
 && ln -sf ${PG_DATADIR}/pg_hba.conf /etc/postgresql/${PG_VERSION}/main/pg_hba.conf \
 && ln -sf ${PG_DATADIR}/pg_ident.conf /etc/postgresql/${PG_VERSION}/main/pg_ident.conf \
 && rm -rf ${PG_HOME} \
 && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y sudo cmake gcc g++ make git \
   libboost-all-dev libfreetype-dev
RUN git clone --depth=1 --single-branch --branch Release_${RDKIT} https://github.com/rdkit/rdkit
WORKDIR /rdkit
RUN rm -rf build && mkdir build && cd build && \
    cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DRDK_INSTALL_INTREE=ON \
    -DRDK_BUILD_CPP_TESTS=OFF \
    -DRDK_BUILD_PYTHON_WRAPPERS=OFF \
    -DRDK_BUILD_COORDGEN_SUPPORT=OFF \
    -DRDK_BUILD_MAEPARSER_SUPPORT=OFF \
    -DRDK_INSTALL_COMIC_FONTS=OFF \
    -DRDK_OPTIMIZE_POPCNT=ON \
    -DRDK_BUILD_TEST_GZIP=ON \
    -DRDK_BUILD_AVALON_SUPPORT=OFF \
    -DRDK_BUILD_INCHI_SUPPORT=ON \
    -DRDK_BUILD_SWIG_WRAPPERS=OFF \
    -DRDK_BUILD_THREADSAFE_SSS=ON \
    -DRDK_TEST_MULTITHREADED=ON \
    -DRDK_BUILD_PGSQL=ON \
    -DRDK_PGSQL_STATIC=ON \
    -DPostgreSQL_CONFIG_DIR=/usr/lib/postgresql/${PG_VERSION}/bin \
    -DPostgreSQL_INCLUDE_DIR="/usr/include/postgresql" \
    -DPostgreSQL_TYPE_INCLUDE_DIR="/usr/include/postgresql/${PG_VERSION}/server" \
    -DPostgreSQL_LIBRARY="/usr/lib/x86_64-linux-gnu/libpq.so"
RUN cd build && make -j `nproc` install
RUN echo "trusted = true" >> /rdkit/Code/PgSQL/rdkit/rdkit.control

FROM postgres:${PG_VERSION}.${PG_VERSION_MINOR} AS prod

ARG PG_VERSION
ARG PG_VERSION_MINOR
ARG RDKIT

COPY --from=rdkit-build /rdkit/Code/PgSQL/rdkit/rdkit.control /usr/share/postgresql/${PG_VERSION}/extension/rdkit.control
COPY --from=rdkit-build /rdkit/build/Code/PgSQL/rdkit/rdkit--4.6.1.sql /usr/share/postgresql/${PG_VERSION}/extension/rdkit--4.6.1.sql
COPY --from=rdkit-build /rdkit/build/Code/PgSQL/rdkit/update_sql/*.sql /usr/share/postgresql/${PG_VERSION}/extension/
COPY --from=rdkit-build /rdkit/build/Code/PgSQL/rdkit/librdkit.so /usr/lib/postgresql/${PG_VERSION}/lib/rdkit.so
COPY --from=rdkit-build /usr/lib/x86_64-linux-gnu/libfreetype.so.6 /usr/include
COPY --from=rdkit-build /usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.74.0 /usr/include
COPY --from=rdkit-build /usr/lib/x86_64-linux-gnu/libpng16.so.16 /usr/include
COPY --from=rdkit-build /usr/lib/x86_64-linux-gnu/libbrotlidec.so.1 /usr/include
COPY --from=rdkit-build /usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1 /usr/include
ENV LD_LIBRARY_PATH=/usr/include
LABEL org.opencontainers.image.source="https://github.com/pechersky/rdkit"
LABEL org.opencontainers.image.version="postgres-${PG_VERSION}.${PG_VERSION_MINOR}-${RDKIT}"
